### PR TITLE
Separate large data from the main application state, store in indexeddb

### PR DESCRIPTION
**Pull request by abrenneke**

### CODE REVIEW

**Comment by Swimburger** [comment]
First of all, the app is only unresponsive for very short times when moving widgets and loading the audio initially, it's totally useable now that it's not frozen all the time!

However, I'm running into these issues:

- The length is NaN it says
- When running, it says "Error: No data at ref ..."
- If I pick a file X, and then change to Y, the Y is only previewed after I move the widgets around a bit. (I don't really care about the preview TBH, I don't know if users would want to play the audio from within Rivet.)
Screenshot 2023-09-11 at 2 46 13 PM

**Comment by abrenneke** [comment]
Got it, let me work on it a bit more

**Comment by abrenneke** [comment]
It's still not going to be ideal because when using the node executor, it's going to need to serialize the whole audio node over the websocket 🤔

**Comment by abrenneke** [comment]
Try latest commit @Swimburger! 
image

**Comment by Swimburger** [comment]
It works on Node executor, but not browser. 
Browser is still saying this: `Error: No data at ref 6YQm4R4c9_RxpK3lRi-Ez`

**Comment by abrenneke** [comment]
Okay all of the above should be fixed now @Swimburger

**Comment by Swimburger** [comment]
Works great, no issues!

**Comment by Swimburger** [comment]
I didn't mean to remove it as draft lol. I was gonna approve.

**Pull request merged**
