### PR TITLE
Fixed Tutorial Bugs and Reduced Total Run Cost

### PR DESCRIPTION
**Pull request by altaiiiir**
Description: Some of the tutorial graphs had some bugs in them. Also, some graphs ran really costly due to using GPT4 by default.

Bug Fixes: Resolved issues in the tutorial that were causing errors.
Cost Optimization: Converted all chat nodes to the cheapest model (GPT3.5 Turbo) to reduce the overall run cost of the application.

Testing:
All tutorial steps were tested and verified.
Monitored cost metrics to confirm reductions.
Passed all unit tests and built successfully.

### CODE REVIEW

**Review by abrenneke — COMMENTED** [review]
Thank you!

**Comment by abrenneke** [comment]
@all-contributors please add @altaiiiir for maintenance

**Comment by krud491** [comment]
Thank you image

**Comment by krud491** [comment]
Here's some art for the time

**Pull request merged**
