### PR TITLE
Use AssemblyAI Node SDK

### PR DESCRIPTION
**Pull request by Swimburger**
I updated the AssemblyAI plugin to use the AssemblyAI Node SDK.
This did require me to polyfill a couple of Node APIs.

### CODE REVIEW

**Comment by abrenneke** [comment]
I'd really prefer to not polyfill node APIs, because Rivet is designed to run without any kind of polyfill. Is there anything we can do to make this or your library isomorphic? It's important to me to keep Rivet isomorphic and not depend on any library that's node or browser specific.

**Comment by abrenneke** [comment]
I suppose that depends on the bundler used. I haven't tested it. I wonder if it's time to move this plugin out of core maybe? Like https://github.com/abrenneke/rivet-plugin-example-python-exec is the example repo. And I just wrote the [docs on creating plugins](https://rivet.ironcladapp.com/docs/user-guide/plugins/creating-plugins) too

**Comment by Swimburger** [comment]
I updated the SDK so it no longer requires polyfills in Rivet. Being built into Rivet was one of the appeals for us to contribute the integration, so I hope we can keep it in, but we can move it out if it makes more sense.

**Comment by abrenneke** [comment]
Sure it's fine! There's really not much difference between built-in plugins and external ones at this point. Built-in plugins allow you to modify the Rivet UI though and add functionality there - if you're only adding nodes, the only real difference is that there's no "install" step and the plugin activates immediately

**Comment by Swimburger** [comment]
We always went the fewest possible steps to success of course. ;) 
Is this PR okay now?

**Review by abrenneke — APPROVED** [review]
Awesome, thanks!

**Comment by abrenneke** [comment]
@Swimburger latest builds have these warnings:

```
[plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "/Users/Shared/ironclad/rivet/.yarn/cache/assemblyai-npm-3.0.1-41a2932ec5-bfa7c25c89.zip/node_modules/assemblyai/dist/index.esm.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "/Users/Shared/ironclad/rivet/.yarn/cache/assemblyai-npm-3.0.1-41a2932ec5-bfa7c25c89.zip/node_modules/assemblyai/dist/index.esm.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

**Comment by Swimburger** [comment]
@abrenneke The plugin doesn't rely on `stream` or `fs`, so we can disregard.
In the next version of the SDK we're using web standard streams tho, so that'll be gone, and we'll have a browser-compatible export that doesn't use `fs` either.

**Pull request merged**
