### PR TITLE
fix: build crashing on Node 20.9.0 or higher

### LINKED ISSUE #260: [Bug]: yarn build fails on Node 20.9.0 (assuming higher as well)
### What happened?

Running `yarn build` using `Node 20.9.0` or high fails with the below build errors. Downgrading to `Node 20.4.0` results in a successful build. Downloads for that version can be found here: https://nodejs.org/dist/v20.4.0/

### What was the expected functionality?

Build should complete without errors, or at consistently on different versions of Node.

### Describe your environment

Happens on both Windows or MacOS, Node 20.9.0 and 20.10.0 releases.

### Relevant log output

```shell
[2:36:37 p.m.] Projects in this build: 
    * tsconfig.json

[2:36:37 p.m.] Project 'tsconfig.json' is out of date because output file 'dist/tsconfig.tsbuildinfo' does not exist

[2:36:37 p.m.] Building project 'C:/work/github/codemile/rivet/packages/core/tsconfig.json'...


node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected array buffer, or typed array to be returned for the "source" from the "transformSource" function but got undefined.
    at __node_internal_captureLargerStackTrace (node:internal/errors:497:5)
    at new NodeError (node:internal/errors:406:5)
    at assertBufferSource (node:internal/modules/esm/translators:84:9)
    at stringify (node:internal/modules/esm/translators:94:3)
    at createCJSModuleWrap (node:internal/modules/esm/translators:219:12)
    at ModuleLoader.commonjsStrategy (node:internal/modules/esm/translators:297:10) {
  code: 'ERR_INVALID_RETURN_PROPERTY_VALUE'
}

Node.js v20.9.0
```

### Relevant screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by codemile**
`tsx` was crashing during builds throwing the error `TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]`. Fix builds by updating `tsx` to latest.

> Note: builds tested again in Node 20.4.0 to ensure this fix doesn't break on people running an older Node.

closes #260

### CODE REVIEW

**Comment by codemile** [comment]
link #260

**Comment by abrenneke** [comment]
I don't see the changes to tarballs in the cache folder being committed, can you commit those changes?

**Comment by codemile** [comment]
@abrenneke updated, the caching on windows is diff. So I update the caches on my Mac. Was going to ask how we could fix this for both OS.

**Comment by abrenneke** [comment]
Yeah I wish there was a solution to the caches changes on different OSes for things like esbuild

**Review by abrenneke — APPROVED** [review]
Thank you! I didn't think of upgrading tsx

**Pull request merged**
