### PR TITLE
LLMRequestResponse interface

### PR DESCRIPTION
**Pull request by galenus**
Initial proposal to allow providing the plugin nodes with same UI and other abilities that 'chat' node benefits from. 
Matching issue: #192 

- LLMRequestResponse interface and its type guards in the 'core' package
- using the new interface in the 'app' package

### CODE REVIEW

**Comment by abrenneke** [comment]
Thank you for this! My main concern is storing the flag in the `data` of the nodes. What if we stored it as a property on the NodeImpl/PluginNodeImpl instead? That way, the data wouldn't get saved into the project file, putting unnecessary noise in it because this this is a property of the node, rather than a piece of configurable data on the node.

**Comment by galenus** [comment]
> Thank you for this! My main concern is storing the flag in the `data` of the nodes. What if we stored it as a property on the NodeImpl/PluginNodeImpl instead? That way, the data wouldn't get saved into the project file, putting unnecessary noise in it because this this is a property of the node, rather than a piece of configurable data on the node.

Good idea, something I completely missed. I will change the code accordingly. 
But I am not sure what to do about PromptDesigner. Maybe, I'll just revert the changes there completely for now, as the scope of the change  to support it properly is much larger.

**Comment by abrenneke** [comment]
Yeah it's tricky, but I really appreciate you thinking about solutions to it!

**Comment by abrenneke** [comment]
Let me know if you ever get back to this @galenus!

**Pull request closed without merging**
