### PR TITLE
Added Anthropic Claude 3 Sonnet and Claude 3 Opus support with Vision capability.

### PR DESCRIPTION
**Pull request by wayne-chang**
- Added Message API support directly.
- Added Claude 3 Sonnet and Claude 3 Opus support.
- Added Vision capability for Claude 3 models.
- Added new "image" port and new "System" port for Claude 3 models.
- Updated anthropic.md help file with new Vision capability.

### CODE REVIEW

**Comment by abrenneke** [comment]
@wayne-chang is this working for you? I had a report that someone tried and they were getting an error about claude 3 requiring some `Messages API` instead of the chat completions one

**Comment by abrenneke** [comment]
> error says: Error: Error processing ChatAnthropicNode: "claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead.

**Comment by wayne-chang** [comment]
> > error says: Error: Error processing ChatAnthropicNode: "claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead.

Addressing!

**Comment by wayne-chang** [comment]
@abrenneke 
image

**Comment by gogwilt** [comment]
@wayne-chang I created #374 with a pretty big update to the Claude 3 support you added. Are you OK if we close this PR and go with the other one?

**Comment by wayne-chang** [comment]
> @wayne-chang I created #374 with a pretty big update to the Claude 3 support you added. Are you OK if we close this PR and go with the other one?

Let's do it!

**Pull request merged**
